apiVersion: apps/v1
apiVersion: v1
kind: Service
metadata:
  labels:
    app: bdp-app
  name: bdp-app
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 80
  selector:
    app: bdp-app
  type: LoadBalancer