apiVersion: apps/v1
kind: Deployment
metadata:
 name: bdp-app
spec:
 strategy:
   rollingUpdate:
     maxSurge: 1
     maxUnavailable: 1
   type: RollingUpdate
 replicas: 1
 selector:
   matchLabels:
     app: bdp-app
 template:
   metadata:
     labels:
       app: bdp-app
   spec:
     containers:
       - name: bdp-app
         image: wwweiweiii/entry_nginx
         ports:
           - containerPort: 80
         env:
          - name: MY_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: MY_POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: MY_POD_IP
            value: MY_NODE_IP