apiVersion: apps/v1
apiVersion: v1
kind: Service
metadata:
  labels:
    app: namenode
  name: namenode
spec:
  ports:
    - port: 9870
      protocol: TCP
      targetPort: 9870
      nodePort: 30070
  selector:
    app: namenode
  type: NodePort