apiVersion: apps/v1
apiVersion: v1
kind: Service
metadata:
  labels:
    app: datanode2
  name: datanode2
spec:
  ports:
    - port: 9864
      protocol: TCP
      targetPort: 9864
      nodePort: 30065
  selector:
    app: datanode2
  type: NodePort